---
:verbose: false
:concurrency: 10
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30
:max_retries: 15

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - ["critical", 1]
  - ["default", 2]
  - ["mailers", 3]
  - ["action_mailbox_incineration", 10]
  - ["action_mailbox_routing", 10]
  - ["active_storage_analysis", 10]
  - ["active_storage_purge", 10]
  - ["low", 30]

# you can override concurrency based on environment
production:
  :concurrency: 25
staging:
  :concurrency: 15
